//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trackingentradaGrupoHumano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCOORDENADA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCOORDENADA()
        {
            this.TBDEPARTAMENTOes = new HashSet<TBDEPARTAMENTO>();
            this.TBENTRADAs = new HashSet<TBENTRADA>();
        }
    
        public int IDCOORDENADA { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public Nullable<int> IDPISO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual TBESTADO TBESTADO { get; set; }
        public virtual TBPISO TBPISO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBDEPARTAMENTO> TBDEPARTAMENTOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBENTRADA> TBENTRADAs { get; set; }
    }
}
