//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trackingentradaGrupoHumano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPERSONA
    {
        public int IDPERSONA { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public string CEDULA { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string LUGARNACIMIENTO { get; set; }
        public string PERSONAGRATA { get; set; }
    
        public virtual TBESTADO TBESTADO { get; set; }
    }
}
